# Generated by Django 5.0.6 on 2024-07-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
